platform :ios, '11.0'

target 'FourSquare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourSquare
  pod 'Alamofire', '4.9.1'
  pod 'PureLayout'


  target 'FourSquareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
